server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    client_max_body_size 50m;

    location /static/ {
        alias /srv/docker/persiamehr/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /srv/docker/persiamehr/media/;
    }

    location /api/ {
        include snippets/proxy-common.conf;
        proxy_pass http://127.0.0.1:8000/api/;
    }

    location /admin/ {
        include snippets/proxy-common.conf;
        proxy_pass http://127.0.0.1:8000/admin/;
    }

    location / {
        include snippets/proxy-common.conf;
        proxy_pass http://127.0.0.1:3001;
    }
}
